version: "3.9"

services:
  database:
    container_name: database
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - 5432:5432
    volumes:
      - nwhacks-db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres=value
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s
  migration:
    container_name: alembic-migration
    build: ./backend
    command: alembic upgrade head
    environment:
      - DATABASE_URL=postgresql://postgres:password@database:5432/postgres
    depends_on:
      database:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./backend/migrations/
  backend:
    container_name: backend
    build: ./backend
    restart: always
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:password@database:5432/postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      migration:
        condition: service_completed_successfully
      minio:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./backend/

volumes:
  nwhacks-db-volume:
  minio_data: