version: "3.9"

services:
  database:
    container_name: database
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - 5433:5432
    volumes:
      - nwhacks-db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres=value
  minio:
    container_name: minio
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s
  memcached:
    container_name: memcached
    image: memcached
    ports:
      - 11211:11211
  migration:
    container_name: migration
    build: ./backend
    command: alembic upgrade head
    environment:
      - DATABASE_URL=postgresql://postgres:password@database:5433/postgres
    depends_on:
      database:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./backend/migrations/
  backend:
    container_name: backend
    build: ./backend
    restart: always
    ports:
      - 8080:8000
    environment:
      - DATABASE_URL=postgresql://postgres:password@database:5433/postgres
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MEMCACHE_HOST=memcached
      - MEMCACHE_PORT=11211
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      migration:
        condition: service_completed_successfully
      minio:
        condition: service_healthy
      memcached:
        condition: service_started
    develop:
      watch:
        - action: rebuild
          path: ./backend/

volumes:
  nwhacks-db-volume:
  minio_data: